image: Visual Studio 2017
version: '{build}'
clone_depth: 100

environment:
  GH_TOKEN:
    secure: gcwQCLzmCp4imjUjTEHrk4HRbEySN8GvDR9LYIstjhPjwBaWEgUZCc0/701b3iU0

cache:
  - basic-miktex-x64.exe -> appveyor.yml

# For debugging
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - if not exist basic-miktex-x64.exe curl -s -o basic-miktex-x64.exe -L https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-2.9.7031-x64.exe
  - basic-miktex-x64.exe --unattended --auto-install=yes --shared --package-set=basic
  - ps: $env:PATH = 'C:\Program Files\MiKTeX 2.9\miktex\bin\x64;' + $env:PATH
  - pdflatex --version
  - xelatex --version
  - ps: cinst -y pandoc --version 1.17.2
  - cmd:  refreshenv

build_script:
  - build.bat no-pause
  - cd doc
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - rake
  - cd ..

test_script:
  - cd msvc/build
  - ctest -C Release --output-on-failure -E shadetest  # CI can't do GPU calcs at this time
  - cd ../..


artifacts:
  - path: msvc/CSE.exe
    name: CSE.exe
  - path: doc/output
    name: Documentation

deploy:
  provider: GitHub
  auth_token:
    secure: gcwQCLzmCp4imjUjTEHrk4HRbEySN8GvDR9LYIstjhPjwBaWEgUZCc0/701b3iU0
  force_update: true
  artifact: CSE.exe
  on:
    appveyor_repo_tag: true

after_deploy:
  # Push docs to GitHub Pages
  - cd doc/output
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:GH_TOKEN):x-oauth-basic@github.com`n"
  - git config --global user.email "ci@cse.org"
  - git config --global user.name "cse-ci"
  - git add -A
  - git commit -m "Update docs for %APPVEYOR_REPO_TAG_NAME%."
  - git push

# Debugging
#on_failure:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
