# Copyright (c) 1997-2016 The CSE Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file.
# The branch in this git repository used for "GitHub Pages"
# see https://pages.github.com/
docs-branch: "gh-pages"
# the source directory for the documentation
src-dir: "src"
# The reference directory with various reference files
reference-dir: "config/reference"
# Path to CSSNano if it is present
# see http://cssnano.co/
cssnano-exe: "node_modules/.bin/cssnano"
# Path to html-minifier
# see https://github.com/kangax/html-minifier
html-minifier-exe: "node_modules/.bin/html-minifier"
# Flag on whether to use Node.js or not
# if yes, node is used to compress the HTML and CSS files
use-node?: false
# Flag on whether or not to use GitHub pages
# if yes, when the documentation is generated, it is set up for easier use to
# push to github pages
use-ghpages?: true
# Flag on whether to build the PDFs or not. Defaults to false since PDF
# requires more dependencies
build-pdf?: false
# Location of the build directory (relative to this file)
build-dir: 'build'
# Location of the final output directory
output-dir: 'build/output'
# URL of the remote origin. This is also the location where the gh-pages branch
remote-repo-url: "https://github.com/cse-sim/cse.git"
# Flag to build under 'draft' status or not
draft?: true
# If true, runs verification after a build to check generated document links
verify-links?: true
# If true, runs verification after a build to check that manifests include all
# files and that all files expected are accounted for
verify-manifest?: true
# Flag to set the verbosity of output
verbose?: false
# Run documentation coverage report by default?
# This report checks doc/config/reference/cullist.txt against what's in the
# documentation to determine if the documentation is covering all topics
coverage?: true
# this variable holds various "flags" to pass into the ERB preprocessor
# NOTE: only define variable keys as standard Ruby variables!
#       for example, "some-variable: 10" would not work since "some-variable"
#       is a valid Ruby name
context:
  build_all: true
  test_erb: false
