name: Build and Test

on: push

jobs:
  build-cse:
    name: Build CSE executable
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        shell: cmd
        run: build.bat no-pause
      - name: Upload executable artifiact
        uses: actions/upload-artifact@v2
        with:
          name: CSE.exe
          path: msvc/CSE.exe
  test-cse:
    name: Test CSE
    needs: build-cse
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure CMake
        run: cmake -P cmake/configure.cmake
      - name: Build wcmp
        run: cmake --build . --config Release --target wcmp
        working-directory: msvc/build
      - name: Download executable artifact
        uses: actions/download-artifact@v2
        with:
          name: CSE.exe
          path: msvc
      - name: Test
        run: ctest -C Release --output-on-failure -E shadetest  # CI can't do GPU calcs at this time
        working-directory: msvc/build
  build-doc:
    name: Build CSE documentation
    needs: build-cse
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure CMake
        run: cmake -P cmake/configure.cmake
      - name: Download executable artifact
        uses: actions/download-artifact@v2
        with:
          name: CSE.exe
          path: msvc
      - name: Build documentation
        uses: .github/workflows/
      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: doc/output