name: Release

on: 
  release:
    types:
      - created

jobs:
  release-cse:
    name: Deploy CSE release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        shell: cmd
        run: build.bat no-pause
      - name: Upload executable to release assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: msvc/CSE.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build documentation
        uses: ./.github/workflows/build-docs/
      - name: Update gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/output
          user_name: 'cse-ci'
          user_email: 'ci@cse.org'
          full_commit_message: "Update docs for ${{ github.event.release.tag_name }}."
